# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoCoder
                                 A QGIS plugin
 This plugin was developed for the “Plugin Development” workshops. It essentially provides a graphical user interface (GUI) for Python’s geopy module.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-10-03
        copyright            : (C) 2026 by Krzysztof Maczynski
        email                : krzysztof.maczynski@student.wat.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoCoder class from file GeoCoder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_coder import GeoCoder
    return GeoCoder(iface)
